import Header from "@/components/dashboard/header";
import Sidebar from "@/components/dashboard/sidebar";
import { Metadata } from "next";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies();
  const metadataCookie = cookieStore.get("metadata");

  return (
    <div className="min-h-screen font-host bg-white antialiased text-neutral-500">
      {metadataCookie?.value ? (
        <div className="flex">
          <Sidebar />
          <div className="flex-1">
            <Header/>
            {children}
          </div>
        </div>
      ) : (
        <p>hello</p>
      )}
    </div>
  );
}
